services:
  # --- LA BASE DE DONNÉES ---
  db:
    image: mysql:8.0
    container_name: mediflow_db_container
    restart: always
    environment:
      MYSQL_DATABASE: mediflow_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../DB.sql:/docker-entrypoint-initdb.d/init.sql

  # --- TON APPLICATION BACKEND ---
  backend:
    build: .
    container_name: mediflow_backend_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker # <--- Active le profil de production Docker

  # --- INTERFACE DE GESTION BD ---
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db