services:
  # --- LA BASE DE DONNÉES ---
  db:
    image: mysql:8.0
    container_name: mediflow_db_container
    restart: always
    environment:
      MYSQL_DATABASE: mediflow_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../DB.sql:/docker-entrypoint-initdb.d/init.sql

  # --- TON APPLICATION BACKEND ---
  backend:
    build: .   # <--- LE POINT SIGNIFIE "ICI" (le dossier actuel)
    container_name: mediflow_backend_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mediflow_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080" # Maps port 8081 on your machine to Adminer's internal port 8080
    depends_on:
      - db