spring.application.name=backend
server.port=8080

# --- PROFIL ACTIF PAR DÉFAUT ---
spring.profiles.active=local

# --- CONFIGURATION JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- CONFIGURATION EMAIL (SMTP GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sososadiqui2004@gmail.com
spring.mail.password=bbwn mcnl ueju lvyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true