spring.application.name=backend
# Connexion à la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/mediflow?useSSL=false&serverTimezone=UTC
spring.datasource.username=root

spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate détectera automatiquement la version de ton MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Port du serveur (pour éviter les conflits si tu lances plusieurs apps)
server.port=8080